FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/frontend/package*.json ./packages/frontend/

ARG APP_SERVER_PORT
ENV REACT_APP_SERVER_PORT=${APP_SERVER_PORT}

RUN npm ci -w packages/frontend/

COPY ./packages/frontend ./packages/frontend/

RUN npm run build -w packages/frontend

EXPOSE 3000

CMD [ "npx", "serve", "-s", "packages/frontend/build" ]